project:
  type: book
  output-dir: docs

book:
  title: "The Data Analyst SQL Cookbook"
  author: "Paulius Alaburda"
  date: "2023-10-18"
  chapters:
    - index.qmd
    - erd.qmd
    - 01-basics.qmd
    - part: The Basics
      chapters:

        - 01-basics/using-sql-in-r.qmd
        - 01-basics/using-sql-in-dbt.qmd
        - 01-basics/joins.qmd
        - 01-basics/window-functions.qmd
        - 01-basics/goodies.qmd
    - part: Data Modelling Techniques
      chapters:
        - 02-models/factless-fact-tables.qmd
        - 02-models/ragged-depth-hierarchies.qmd
    - part: Data Recipes
      chapters:
        - 03-recipes/joins.qmd
        - 03-recipes/queries_with_dates.qmd
        - 03-recipes/pivoting-and-unpivoting.qmd
        - 03-recipes/filtering.qmd
        - 03-recipes/customer-analytics.qmd
    - goodies.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



